name: Preprocessor

on:
  push:
    branches: ['main']
    paths:
      - '**/preprocessor.*'
      - 'sub/*.json'
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run script
        run: php edge/preprocessor.php

      - name: Configure git
        run: |
          git config --local user.name "BotFather"
          git config --local user.email "BotFather.rev@proton.me"

      - name: Commit changes
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Cloudflare IPs Refreshed at: $(TZ='Asia/Tehran' date '+%H:%M:%S')" \
                         -m "The list of Cloudflare IPs has been updated" \
                         --author="Diana-Cl <135276904+Diana-Cl@users.noreply.github.com>"
          else
            echo "No changes detected. Skipping commit."

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
