name: REvil Warp generator

on:
  push:
    branches: [ "main" ]
    paths:
      - 'warp.py'
  schedule: #every fuckin 60 minutes
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp.py
    - name: Commit and push changes
      run: |          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config credential.helper store
          git add -A
          git commit -m "ⅣⅭ Updated: $(TZ='Asia/Tehran' date '+%l:%M %p, %A, %d %b %Y')"
          git push
