name: RE Python

on:
  push:
    branches: [ "main" ]
    paths:
      - 'warp.py'
  schedule: #every fuckin 60 minutes
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
   
    - name: Run script
      run: python warp.py
    - name: Commit and push changes
      run: |          
          git config --global user.email "nirevil@proton.me"
          git config --global user.name "REvil"
          git config credential.helper store
          git add -A
          git commit -m "ⅨⅣⅭⅯ UPDATED"
          git push
