name: Spring

on:
  push:
    branches: ['main']
    paths:
      - '**/spring.*'
      - 'edge/assets/*.json'
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Python environments
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          architecture: x64

      # Cache Python shits
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # install Python ip tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip || exit 1
          pip install -r edge/requirements.txt || exit 1

      # Run spring to fetch warp IP's and create wireguard configurations
      - name: Run python
        run: python edge/spring.py

      # Commit and push if chanes
      - name: Commit and push if changed
        run: |
          git config --local user.name "Diana-Cl"
          git config --local user.email "135276904+Diana-Cl@users.noreply.github.com"
          git add *.json
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Task done $(TZ='Asia/Tehran' date '+%H:%M:%S')" -m "wireuard private key, addresses, reserved and all IPs have been renewed"
            git -c author.name="Diana-Cl" -c author.email="135276904+Diana-Cl@users.noreply.github.com" \
                -c committer.name="github-actions[bot]" -c committer.email="41898282+github-actions[bot]@users.noreply.github.com" \
                commit --amend --no-edit
          )
          git push
          
